export const POSSIBLE_ACTIONS = {
  SET_CATEGORIES_START: "category/SET_CATEGORIES_START",
  SET_CATEGORIES_SUCCESS: "category/SET_CATEGORIES_SUCCESS",
  SET_CATEGORIES_ERROR: "category/SET_CATEGORIES_ERROR",
};
